SELECT 
    E.EMP_ID, 
    E.FIRST_NAME, 
    E.LAST_NAME, 
    D.DEPARTMENT_NAME,
    (
        SELECT COUNT(*) 
        FROM EMPLOYEE E2 
        WHERE 
            E2.DEPARTMENT = E.DEPARTMENT 
            AND E2.DOB > E.DOB
    ) AS YOUNGER_EMPLOYEES_COUNT
FROM EMPLOYEE E
JOIN DEPARTMENT D
    ON E.DEPARTMENT = D.DEPARTMENT_ID
ORDER BY E.EMP_ID DESC;
